# Generated by Django 4.2.30 on 2026-09-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('produtor', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('cultura', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umidade_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temperatura_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_colheita', 'Em colheita')], default='ativo', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='talhoes/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='lavoura.talhao')),
            ],
        ),
    ]
